#pragma once
#include<iostream>
#include <cmath>
#include <string>
#include <windows.h>
#include <winuser.h>                                                     
#include <conio.h>  
#include <stdlib.h>
#include <dos.h>
#include <stdio.h>
#include <fcntl.h>
#include <locale.h>
#include <chrono>
#include <thread>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <random>
#include <ctime>
#include <map>